name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Inject secret and build
      env:
        STATION_API_KEY: ${{ secrets.STATION_API_KEY }}
      run: |
        echo "export const apiKey = '${STATION_API_KEY}';" > js/config.js
        # Ici tu peux lancer ta build, par exemple avec npm run build
        # npm run build

    # Tu peux ajouter une étape pour déployer ou copier les fichiers construits