name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Inject secret and build
      env:
        STATION_API_KEY: ${{ secrets.STATION_API_KEY }}
      run: |
        echo "export const apiKey = \"${STATION_API_KEY}\";" > js/config.js
        ls -l js/
        cat js/config.js
        cp js/config.js js/config.js