name: Deploy on main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate config.js with secret
        run: |
          echo "const CONFIG = {" > config.js
          echo "  STATION_API_KEY: '${{ secrets.STATION_API_KEY }}'" >> config.js
          echo "};" >> config.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add config.js
          git commit -m "Update config.js with secret"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}